/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WisdomRouteImport } from './routes/wisdom'
import { Route as MapRouteImport } from './routes/map'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as AlumniIdRouteImport } from './routes/alumni.$id'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as ApiAuthLinkedinStartRouteImport } from './routes/api/auth/linkedin/start'
import { Route as ApiAuthLinkedinCallbackRouteImport } from './routes/api/auth/linkedin/callback'

const WisdomRoute = WisdomRouteImport.update({
  id: '/wisdom',
  path: '/wisdom',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AlumniIdRoute = AlumniIdRouteImport.update({
  id: '/alumni/$id',
  path: '/alumni/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiAuthLinkedinStartRoute = ApiAuthLinkedinStartRouteImport.update({
  id: '/api/auth/linkedin/start',
  path: '/api/auth/linkedin/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLinkedinCallbackRoute = ApiAuthLinkedinCallbackRouteImport.update({
  id: '/api/auth/linkedin/callback',
  path: '/api/auth/linkedin/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/companies': typeof CompaniesRoute
  '/directory': typeof DirectoryRoute
  '/map': typeof MapRoute
  '/wisdom': typeof WisdomRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/alumni/$id': typeof AlumniIdRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/api/auth/linkedin/callback': typeof ApiAuthLinkedinCallbackRoute
  '/api/auth/linkedin/start': typeof ApiAuthLinkedinStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/companies': typeof CompaniesRoute
  '/directory': typeof DirectoryRoute
  '/map': typeof MapRoute
  '/wisdom': typeof WisdomRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/alumni/$id': typeof AlumniIdRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/api/auth/linkedin/callback': typeof ApiAuthLinkedinCallbackRoute
  '/api/auth/linkedin/start': typeof ApiAuthLinkedinStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/companies': typeof CompaniesRoute
  '/directory': typeof DirectoryRoute
  '/map': typeof MapRoute
  '/wisdom': typeof WisdomRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/alumni/$id': typeof AlumniIdRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/api/auth/linkedin/callback': typeof ApiAuthLinkedinCallbackRoute
  '/api/auth/linkedin/start': typeof ApiAuthLinkedinStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/companies'
    | '/directory'
    | '/map'
    | '/wisdom'
    | '/messages'
    | '/onboarding'
    | '/profile'
    | '/alumni/$id'
    | '/auth/verify'
    | '/api/auth/linkedin/callback'
    | '/api/auth/linkedin/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/companies'
    | '/directory'
    | '/map'
    | '/wisdom'
    | '/messages'
    | '/onboarding'
    | '/profile'
    | '/alumni/$id'
    | '/auth/verify'
    | '/api/auth/linkedin/callback'
    | '/api/auth/linkedin/start'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/companies'
    | '/directory'
    | '/map'
    | '/wisdom'
    | '/_authenticated/messages'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/alumni/$id'
    | '/auth/verify'
    | '/api/auth/linkedin/callback'
    | '/api/auth/linkedin/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  CompaniesRoute: typeof CompaniesRoute
  DirectoryRoute: typeof DirectoryRoute
  MapRoute: typeof MapRoute
  WisdomRoute: typeof WisdomRoute
  AlumniIdRoute: typeof AlumniIdRoute
  ApiAuthLinkedinCallbackRoute: typeof ApiAuthLinkedinCallbackRoute
  ApiAuthLinkedinStartRoute: typeof ApiAuthLinkedinStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wisdom': {
      id: '/wisdom'
      path: '/wisdom'
      fullPath: '/wisdom'
      preLoaderRoute: typeof WisdomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/alumni/$id': {
      id: '/alumni/$id'
      path: '/alumni/$id'
      fullPath: '/alumni/$id'
      preLoaderRoute: typeof AlumniIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/auth/linkedin/start': {
      id: '/api/auth/linkedin/start'
      path: '/api/auth/linkedin/start'
      fullPath: '/api/auth/linkedin/start'
      preLoaderRoute: typeof ApiAuthLinkedinStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/linkedin/callback': {
      id: '/api/auth/linkedin/callback'
      path: '/api/auth/linkedin/callback'
      fullPath: '/api/auth/linkedin/callback'
      preLoaderRoute: typeof ApiAuthLinkedinCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  CompaniesRoute: CompaniesRoute,
  DirectoryRoute: DirectoryRoute,
  MapRoute: MapRoute,
  WisdomRoute: WisdomRoute,
  AlumniIdRoute: AlumniIdRoute,
  ApiAuthLinkedinCallbackRoute: ApiAuthLinkedinCallbackRoute,
  ApiAuthLinkedinStartRoute: ApiAuthLinkedinStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
